### ISSUE TITLE
No 'config.undefined.js' file found

### ISSUE THREAD

**Issue by pazitron1** [maizzle/framework#35]
- Maizzle/CLI Version: 0.2.1
- Maizzle/framework Version: 0.3.0
- Node.js Version: 10.16.1

### Description:

The maizzle/framework v 0.3.0 has the following issues when running maizzle serve:

(node:17474) UnhandledPromiseRejectionWarning: Error: No 'config.undefined.js' file found
(node:17474) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:17474) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code

### Steps To Reproduce:
Update/install maizzle/framework v.0.3.0
Create new maizzle project and cd
run maizzle serve

### Workaround
in your terminal run touch config.undefined.js
then maizzle serve

**Comment by cossssmin** [comment]
Crap, I think I know what caused it. Thanks for flagging, I’ll fix it next week when I return from vacation.

**Comment by cossssmin** [comment]
Fixed in `v0.3.1`, make sure to update and thanks again for letting me know 👍

**Comment by happysalada** [comment]
@cossssmin 
I've got the same issue still.
Here are the exact steps I took
```
# install maizzle
yarn global add @maizzle/cli
maizzle new my_project
cd my_project
maizzle serve
```
maizzle cli version: 0.1.2

Anything I forgot to do? I just followed the official tutorial

**Comment by cossssmin** [comment]
Can you please run `npm list @maizzle/framework` in your project, and let me know what framework version are you using?

**Comment by happysalada** [comment]
@cossssmin thanks for the help! The framework version was actually the old one.
on a fresh install for a new maizzle project it seems to default to the old framework version, that tricked me.
Thanks for your time!

**Comment by cossssmin** [comment]
Cool, happy to hear it worked. I should update that `package-lock.json` on the starter...
