### ISSUE TITLE
Maizzle is parsing {{ }} even if they are inside if condition tag with not satisfied condition

### ISSUE THREAD

**Issue by schirliuradu** [maizzle/framework#354]
- Maizzle Version: 2.4.1
- Node.js Version: 12.19.0

Hi Cosmin. 

While playing a bit more with maizzle events and data coming from "outside" (api for example), i noticed a weird behaviour. 

Let's suppose that you have an api returning an object of something, that you save under `config.templateData`. You can access this object and everything could be inside it through `page.templateData` into your templates/components files. If you have a situation like this:

```
<extends src="src/layouts/master.html">
    <block name="template">
        
        <table class="w-full">
            <tr>
                <th>
                    <if condition="page.templateData">
                        
                        {{ page.templateData.introBox.title }}

                    </if>

                </th>
            </tr>
        </table>

    </block>
</extends>
```

The behaviour that everybody (i think) would expect from this code is that if the object is undefined (for random reasons) you skip all code that is inside ``if`` condition tag. Well, here is the weird behaviour.  If you don't have that object, it returns undefined and the if condition is skipped, but maizzle (or better, i thing it's posthtml-expressions in this case) reads the content inside curly braces `{{  }}` and tries to parse it, even if it should be bypassed because condition is not satisfied. 

The error that maizzle throws is that i try to access a `title` property on undefined. Well, if i control that just external object exists, and if not exists, it shout not care about what i'm trying to do inside that if condition block. It should just escape everything, bypass it. It shoud not be his business what i am trying to do and what variables i'm trying to access inside that if block. 

Same situation if you try to instantiate a new component inside that if block if condition is satisfied, without passing nothing into locals of that component. But, if you try to access the same variable into that component's definition it tries to parse it, and this is totally wrong. If the condition is not satisfied, it should just escape it. 

This is what i mean in this second case:

```
<extends src="src/layouts/master.html">
    <block name="template">
        
        <table class="w-full">
            <tr>
                <th>
                    <if condition="page.templateData">
                        
                        <component src="src/components/testcomponent.html"></component>

                    </if>

                </th>
            </tr>
        </table>

    </block>
</extends>
```
and this is what i have inside testcomponent file
```
<table class="w-full">
    <tr>
        <th>

            {{ page.templateData.introBox.title }}

        </th>
    </tr>
</table>
```

Let me know please what do you think about this. Thank you.

**Comment by cossssmin** [comment]
The `<if>` tag checks for a truthy condition in `posthtml-expressions` afaik. 

Is `page.templateData` undefined, or an empty object?

**Comment by schirliuradu** [comment]
``page.templateData`` is undefined

**Comment by schirliuradu** [comment]
The problem is not that the object is undefined or empty. The problem is, as i see it, the fact that if you assign value ``5`` or random string to ``templateData`` instead of undefined or just empty object, and then you check inside if condition if page.templateData == 3 or everything else, just for having ``false`` result and not parse the block that is inside the if condition, the block inside if condition is parsed, even if condition is not true

**Comment by cossssmin** [comment]
Modified the [`conditional_if_key_not_exists`](https://github.com/posthtml/posthtml-expressions/blob/master/test/fixtures/conditional_if_key_not_exists.html) test in `posthtml-expressions` and looks like it's failing there, indeed:

```html
<if condition="key_not_exists">
  {{ key_not_exists.foo }}
  it works!
</if>
```

👇

```sh
Rejected promise returned by test. Reason:

ReferenceError {
  message: 'key_not_exists is not defined',
}
```

Fails only when trying to access a property of an undefined variable, this works just fine:

```html
<if condition="key_not_exists">
  {{ key_not_exists }}
  it works!
</if>
```

This needs to be handled in posthtml-expressions - will open an issue there, thanks for reporting it 👍

**Comment by cossssmin** [comment]
We'll need `{ strictMode: false }` as default for `posthtml-expressions` in Maizzle no matter if that will/can be fixed at the source, since right now you need to set it manually in the config and this won't work out of the box either:

```html
<if condition="key_not_exists">
  {{ key_not_exists }}
  it works!
</if>
```

**Comment by schirliuradu** [comment]
i'm not sure this parameter set to false solves the problem. Even after trying to set it directly in posthtml expressions into node modules plugin folder (just for testing it) to false, i'm still having same problem. Am i missing something?

**Comment by schirliuradu** [comment]
I made some more tests and i think we are good with strictMode to false. Just one thing left to understand: will you release a new fix with strictMode: false default in maizzle or we have to set it in config file?

**Comment by schirliuradu** [comment]
Setting it from config file will not work. If you set it from there(config file) and console.log it into ``node_modules/posthtml-expressions/lib/index.js`` after options you'll have it to false just the first time. From second time it's true again, so it doesn't work. There are more than 2 times if you include at least 1 component into your templates. Same issue when you have nested components. 

Am i doing something in a wrong way? 

I'm setting strictMode in this way:

```
    posthtml: {
      expressions: {
        strictMode: false,
      }
    }
```

![Schermata da 2020-11-09 15-13-25](https://user-images.githubusercontent.com/48323576/98551952-34be5c80-229e-11eb-99dd-16f1dff03382.png)

If you set it directly into ``node_modules/posthtml-expressions/lib/index.js`` to false, then you have ``false`` everytime. 

![Schermata da 2020-11-09 15-15-16](https://user-images.githubusercontent.com/48323576/98552140-66cfbe80-229e-11eb-9f1a-6880e20b8b14.png)

**Comment by cossssmin** [comment]
Ah no, I meant we would have had to set it to true by default because right now it fails even when trying to access the object directly, let alone an undefined property on it. Gonna pull in posthtml-expressions 1.6.1 and test with it, it might be fixed now and we should just have to bump the dependency - will try it tonight.

Side note: 5 seconds for that build 😲 - are you using many components in the template? Because it shouldn't take that much for a regular...ish template.

**Comment by schirliuradu** [comment]
Ok, perfect. Let me know when we can try the fix. For the compiling time, yeah, it's just because of external api, and i'm also doing some small regexes, but it's just for testing purposes. Let me know, and thank you one more time :)

**Comment by cossssmin** [comment]
Just tried it and it's fixed in 1.6.1, this:

```html
<if condition="page.templateData">
  {{ page.templateData.introBox }}
</if>
<else>
  works
</else>
```

renders:

```html

works

```

Will add it in the next release which will be published this week - just need to get in the other things like exposing Transformers and a few other features 👍

**Comment by schirliuradu** [comment]
Ok, i'll wait for the fix and try it as soon as you publish it and let you know. Thank's

**Comment by schirliuradu** [comment]
Hi Cosmin, 

I'm still having some issues regarding this argument. 

Considering the fact that we can not pass "dynamic" data to components (data coming from an api for example, that we have already discussed in this issue #336), i tried to access data directly from page (or global locals introduced in maizzle 2.5.0) inside components. 

Let suppose that i have some sections in my template, and want to render then conditionally. I'll paste here a small example:

template
```
<extends src="src/layouts/master.html">
   
  <block name="content">
    <table class="content-wrapper-table py-4 w-full">
      
      <if condition="page.apiData">
        <tr>
          <th class="px-14 sm-px-8">
            <component src="src/components/testcomponent.html"></component>
          </th>
        </tr>
      </if>

    </table>
  </block>

</extends>
```

component definition

```
 <table class="w-full">
  <tr>
    <th>
      <table class="w-full">
        <if condition="page.apiData.title">
          <tr>
            <th>
              {{ page.apiData.title }}
            </th>
          </tr>
        </if>

        <if condition="page.apiData.itemsList && page.apiData.itemsList.length > 0">
          <tr>
            <th>
              <each loop="item, key in page.apiData.itemsList">
                <tr>
                  <th>
                    {{ item.text }}
                  </th>
                </tr>
              </each>
            </th>
          </tr>
        </if>
      </table>
    </th>
  </tr>
</table>
```

Even after fixing current issue, in this example happens same thing: i check if items list exists with an if condition and if doesn't it should just bypass it. But it tries to parse it anyway, and i have a loop error, just as here #336 

```
⚠ Cannot read property 'itemsList' of undefined
```

This error happens on ``each`` loop when i try to access a property of undefined. If object coming from api is not undefined but an empty object, there's a loop error, because it doesn't have an array on which execute the loop (there will be the apiData object (but empty) but itemsList will be undefined).

**Comment by cossssmin** [comment]
What `posthtml-expressions` versions do you see when running `npm list posthtml-expressions` in your project? Should be 1.6.1 everywhere (remove `node_modules` and `package-lock.json` and reinstall if not). 

Asking because I just tested your code and I'm getting a different error, not that `itemsList` is `undefined` - that `if` statement is properly ignored.

The error I'm getting is [thrown](https://github.com/posthtml/posthtml-expressions/blob/5a883311929ad53b44f3b51b9bd05af7f1eb0ef2/lib/index.js#L348) by `posthtml-expressions`, the variable provided to the loop must be an object:

```js
// handle additional syntax errors
if (typeof target !== 'object') {
  throw new Error('You must provide an array or object to loop through')
}
```

I think the plugin could do a check for `strictMode` and throw only if that is `true`. I'll bring it up with the team.

For reference, here's your slightly modified component that I used for testing:

```html
<if condition="page.apiData.title">
  <h3>{{ page.apiData.title }}</h3>
</if>

<if condition="page.apiData.itemsList && page.apiData.itemsList.length > 0">
  <table class="w-full">
    <each loop="item, key in page.apiData.itemsList">
      <tr>
        <th>
          {{ item.text }}
        </th>
      </tr>
    </each>
  </table>
</if>
```

And my `config.js` includes the `apiData.title`:

```js
module.exports = {
  apiData: {
    title: 'title from api'
  },
}
```

When building this, I get the `You must provide an array or object to loop through` error.

If I go to `posthtml-expressions` and modify it so it looks like this:

```js
// handle additional syntax errors
if (typeof target !== 'object' && opts.strictMode) {
  throw new Error('You must provide an array or object to loop through')
}
```

... it compiles without errors and:

- `<h3>` is output as expected
- the `<table>` is not output, meaning `if` condition is working as expected, and the type check only throws if we're in `strictMode` (which Maizzle always sets to `false`)

**Comment by schirliuradu** [comment]
I have 1.6.1, but deleted and reinstalled all dependencies again. Result is the same. You have the error on loop because the apiData object was defined (NOT undefined), but it hasn't inside the property i need to loop on. 

I tried with ``&& opts.strictMode`` on line where the loop error is thrown and it seems to solve the loop issue, so i think we have to make a PR to add this to posthtml-expressions. Anyway, if you have an undefined object that you try to access you still get same error (trying to read property "something" of undefined).

Even if you have the apiData defined, but you have 2 annidation levels inside it, youll'have the same issue trying to access that second level of annidation.

I mean something like this:

```
module.exports = {
  apiData: {
    title: 'title from api'
  },
  itemsList: {
    items: []
  }
}
```

If you have to iterate on ``apiData.itemsList.items`` (i know this doesn't make sense but i could have an example like this), but you have just title inside there (no itemsList and no items), that youll'get same error 
```
module.exports = {
  apiData: {
    title: 'title from api'
  },
}
```

**Comment by cossssmin** [comment]
You're right, sorry :)

So [this](https://github.com/posthtml/posthtml-expressions/blob/5a883311929ad53b44f3b51b9bd05af7f1eb0ef2/lib/index.js#L344) uses Node's `vm` to run code in a context - the code in this case is your condition inside the `if` statement, and the context is the `page` object. Normally this fails, since that is the correct behavior when running this in JS with `api` being undefined:

```js
if (page.api.items && page.api.items.length > 0) {
  console.log("foo")
}

// TypeError: Cannot read property 'items' of undefined
```

Ideally, `posthtml-expressions` could do a try/catch there:

Reported and will be fixed in the next `posthtml-expressions` release - see https://github.com/posthtml/posthtml-expressions/commit/d14fbbb683460fad4f8b2edb649f9ef759b89038

**Comment by cossssmin** [comment]
`posthtml-expressions@1.6.2` has been released, tested and it works fine - will publish a patch today.

Thanks for reporting this and helping improve Maizzle 👍

**Comment by cossssmin** [comment]
@schirliuradu published [`2.6.1`](https://github.com/maizzle/framework/releases/tag/v2.6.1)

**Comment by schirliuradu** [comment]
Still having this issue if object on which i should loop is undefined. Take a look at this [repo](https://github.com/schirliuradu/maizzle-test). 

If we add this condition `` && opts.strictMode `` in posthtml-expressions everything seems to work fine (with strictMode to false (maizzle default)) 
```
// handle additional syntax errors
if (typeof target !== 'object' && opts.strictMode) {
  throw new Error('You must provide an array or object to loop through')
}
```

**Comment by rrj-dev** [comment]
> Still having this issue if object on which i should loop is undefined. Take a look at this [repo](https://github.com/schirliuradu/maizzle-test).
> 
> If we add this condition `&& opts.strictMode` in posthtml-expressions everything seems to work fine (with strictMode to false (maizzle default))
> 
> ```
> // handle additional syntax errors
> if (typeof target !== 'object' && opts.strictMode) {
>   throw new Error('You must provide an array or object to loop through')
> }
> ```

I'm having the same issue too
