### ISSUE TITLE
Bug: Templates receive wrong config on re-render

### ISSUE THREAD

**Issue by jsbrain** [maizzle/framework#885]
- Maizzle Version: 4.x
- Node.js Version: 19

The feature introduced in [4.1.0](https://github.com/maizzle/framework/releases/tag/v4.1.0#:~:text=font%2Dface%20declarations.-,build.current.path,-The%20config%20now) has a bug so that the `config.build.current` object work when saving the `config.js` file (each template file get's the correct html + config combination holding the `config.build.current` data) but receives a _stale_ or rather _wrong_ config object when triggering re-render because of template file changes.

So let's say we have 2 templates, `a.html` and `b.html` and we add a `beforeRender` event that logs the current template file name:

```js
console.log('beforeRender:', config.build.current.path.name)
```

When starting the project (`yarn dev`), and saving the `config.js` file, the console would log:

```
...
beforeRender: a
beforeRender: b
...
```

as the config get's properly updated for each template.

But when we open and save one of the templates, the log will be "out of sync".

So if we first open and save file `a.html`, then file `b.html`, the console would log:

```
...
beforeRender: a
beforeRender: a
...
```

I think somehow the watch method does not correctly update the config update in regards of the `config.build.current` object.

I tried to figure out what the problem is but kinda got lost tbh and I imagine you probably already have a clue while reading this.

To reproduce the problem with logs: https://github.com/jsbrain/maizzle-render-bug

**Comment by jsbrain** [comment]
I just noticed, that when opening and saving a component for example, the correct watch hook is triggered and the configs get passed properly again.

I think it has somehow to do with [this line here](https://github.com/maizzle/framework/blob/5f3c2d9fc3c69f68c09e6aa1777e2ed743db206f/src/commands/serve.js#L100) that ignores the templates directory. When saving a template the console only logs `Compiled in x.xxxs <path to tempate>` but on basically any other file it logs `Re-built x templates in x.xxxs`.

**Comment by jsbrain** [comment]
Just confirmed. Removing `{ignored: templatePaths}` makes it works, but obviously triggers duplicate re-render.

**Comment by cossssmin** [comment]
Hi there, thanks for taking the time to investigate and report this.

This happens because the config is not re-computed when making changes to a template file, but it _is_ re-computed when everything is rebuilt.

When developing locally, updates to a single template file are separated from changes to files that have a global impact: we only re-render _that_ template, so the change happens much faster. Currently, when this happens, existing config data is used, which is why you're not seeing changes reflected when updating your config while the server is running.

In contrast to templates, changes to any other files that are watched (layouts, components, configs) impact every other file too, so they need to trigger a full rebuild. This "full rebuild" also re-runs the config resolver, which is why you see it working in this case. 

You can see that when we re-render templates on their own [here](https://github.com/maizzle/framework/blob/5f3c2d9fc3c69f68c09e6aa1777e2ed743db206f/src/commands/serve.js#L50-L96), the config is not re-computed, but when any other files are changed, we [trigger the full rebuild](https://github.com/maizzle/framework/blob/5f3c2d9fc3c69f68c09e6aa1777e2ed743db206f/src/commands/serve.js#L99-L102) that will also re-compute the config.

This config "caching" behavior is more of a leftover of past behavior when updates to a single template triggered the full rebuild.

We could obviously try to re-compute the config on every template change, I think there won't be any significant speed impact. 

The only issue I can see is that items that are removed from a config while the server is running will still be available until you stop the server, so imagine:

1. start server
1. add `foo: 'bar'` to `config.js`, save file
1. save `src/templates/example.html` => `page.foo` is available
1. remove `foo: 'bar'` from `config.js`, save file
1. save `src/templates/example.html` => `page.foo` is _still_ available

This would, again, only happen when developing locally with `maizzle serve` / `npm run dev`.

I'll try to whip up a PR to include in the upcoming `4.4.0`, thanks again for taking the time 👍

**Comment by cossssmin** [comment]
This should now be fixed in the latest `4.4.0` beta: https://github.com/maizzle/framework/releases/tag/v4.4.0-beta.7

**Comment by jsbrain** [comment]
Maybe I'm doing something wrong but it's still not working for me.

To reproduce:

- Clone https://github.com/jsbrain/maizzle-render-bug
- Run it
- Go to `nested.html` and save the file
- Console will show `... should be nested but is transactional`

**Comment by cossssmin** [comment]
Oh, that's something else, but it needs fixing too.

So the initial issue with the config has been resolved, but what you're asking about now has to do with a config key that isn't currently available when developing locally.

```js
console.log(
  `\n -> should be: ${extracted} but is ${config.build.current.path.name}`
);
```

`config.build.current` is not currently set/updated when developing locally (`maizzle serve` or `npm run dev`), it's only available when running the build command (`maizzle build ...` or `npm run build`).

It's always showing `transactional` because that's the last file it parsed when it started the local dev server.

I'll try to add a fix for this over the weekend, thanks for spotting it 👍

**Comment by cossssmin** [comment]
Released `4.4.0-beta.9`, `config.build.current` should now be properly updated when saving a template while developing locally.

**Comment by jsbrain** [comment]
Only did a quick test but seems to work now.

Thank you so much!
